version: "3.2"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # env_file:
    #   - ./.env
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: npm run dev
