/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a5fef26c-9f5f-41cc-b096-c81d89fb0dc7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_EJfEdlKJ4",
    "aws_user_pools_web_client_id": "29iqblp42pvf84rqql6k2ti36s",
    "oauth": {}
};


export default awsmobile;
